---
# Distribution Center parameters - This section will be specific to a Distribution Center.
deployment_log: "/usr/src/cloud-development/logs/vc01_deployment.log"
vsphere_server: "vc01.h2o-75-9210.h2o.vmware.com"
vsphere_username: "administrator@vsphere.local"
vsphere_password: "prompt"
supervisor_cluster: "vc01cl01-wcp.h2o-75-9210.h2o.vmware.com"

# What is the vsphere cluster name?
cluster_name: vc01cl01
vsphere_datacenter: vc01
storage_class: "vc01cl01-t0compute"
datastore: "vsanDatastore"
distributed_switch: "vc01-dvs"
content_library: "vc01cl01-wcp"

# Workload Management settings...
vsphere_namespace: "atl1-tkgs-ns1"
workload_cluster: "atl1-tkgs-workload"

# Network settings for the Supervisor cluster...
supervisor_network_starting_ip: "10.220.30.139"
supervisor_network_subnet_mask: "255.255.255.224"
supervisor_network_gateway_ip: "10.220.30.158"
supervisor_network_static_ip_pool: "10.220.30.144-10.220.30.157"
# UNUSED: supervisor_distributed_port_group: "esxi-mgmt"
supervisor_network_name: "esxi-mgmt"
supervisor_network_static_address_count: "5"

# Workload network
primary_workload_network_ip: "10.220.47.0/26"
primary_workload_network_static_gateway_ipv4: "10.220.47.62"
primary_workload_network_static_starting_address_ipv4: "10.220.47.12"
primary_workload_network_static_address_count: "50"
primary_workload_network_static_subnet_mask: "255.255.255.192"
primary_workload_network_vsphere_portgroup_name: "user-workload"

# Data network (VIP network)
data_network_ip: "10.220.47.0/26"
data_network_static_starting_address_ipv4: "10.220.47.1"
data_network_static_address_count: "11"
data_network_gateway_ip: "10.220.47.62"
data_network_vsphere_portgroup_name: "user-workload"

dns_servers: "10.220.136.2,10.220.136.3"
dns_search_domain: "h2o-75-9210.h2o.vmware.com"
ntp_servers: "time1.oc.vmware.com,time2.oc.vmware.com,time3.oc.vmware.com,time4.oc.vmware.com"

avi_controller_ip: "avi.h2o-75-9210.h2o.vmware.com"
avi_network: "esxi-mgmt"
avi_subnet_mask: "255.255.255.224"
avi_network_ip: "10.220.30.128/27"
avi_default_gateway: "10.220.30.158"
avi_content_library: "avi"
avi_ova_name: "controller-22.1.3-9096"
avi_vm_name1: "avi01"
avi_vm_ip1: "10.220.30.131"
avi_vm_name2: "avi02"
avi_vm_ip2: "10.220.30.132"
avi_vm_name3: "avi03"
avi_vm_ip3: "10.220.30.133"
avi_floating_ip: "10.220.30.134"
# The AVI Service Engine IPs are allocated out of the IP Pool

# This cert is used by vSphere to talk to AVI. 
avi_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDRTCCAi2gAwIBAgIUUhABp7kmFK995Awju2kdiUS9xtUwDQYJKoZIhvcNAQEL
  ...
  PDc+OKrhC1mvlALt2idQuJtcJ6K4MvaNYw==
  -----END CERTIFICATE-----

avi_root_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDRTCCAi2gAwI...
  -----END CERTIFICATE-----

avi_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQ...
  -----END RSA PRIVATE KEY-----

avi_passphrase: ""
avi_root_cert_name: "avi-root"
avi_controller_cert_name: "avi-controller"

splunk_url: "http-inputs-mck.splunkcloud.com"
splunk_port: "443"
splunk_token: "redacted"
# #################################################################################
# This section contains parameters that are the same for each Distribution Center...
vsphere_namespace_owner: "tkg-admin"
vsphere_namespace_owner_domain: "local.os"


tkg_user: "tkg-admin"
tkg_user_password: "prompt"
tkg_role: tkg

# AVI user in vSphere used to deploy AVI Controller and SEs...
avi_vsphere_username: "avi-admin"
avi_vsphere_password: "prompt"
avi_role: "avi"
avi_ipam_provider_name: "vip-data-network"
# UNUSED: avi_vsphere_resource_pool: "avi"

# Admin username inside the AVI system; Use this to get access in the AVI UI.
avi_username: "admin"
avi_password: "prompt"
avi_resource_pool: "avi"

cp_vmclass_size: "best-effort-medium"
control_plane_count: "1"
worker_node_count: "3"
worker_vmclass_size: "best-effort-2xlarge"
varlib_disksize: "115Gi"
ctrd_disksize: "25Gi"
kubelet_disksize: "15Gi"
tkr: "v1.22.9---vmware.1-tkg.1.cc71bc8"
#tkr: "v1.23.8---vmware.3-tkg.1"

tanzu_package_registry: "projects.registry.vmware.com/tkg/packages/standard/repo"
tanzu_package_registry_version: "v1.6.1"
tanzu_standard_package_repo_name: "tanzupackages"
installed_packages_namespace: "tanzu-packages"

# Unused below here
avi_ca_data_b64: 
avi_cloud_name: 
avi_control_plane_ha_provider: "true"
avi_controller: 
avi_data_network: 
avi_data_network_cidr: 
avi_enable: "true"
avi_labels: ""
avi_management_cluster_vip_network_name: 
avi_management_cluster_vip_network_cidr: 
avi_service_engine_group: 

cluster_cidr: 100.96.0.0/11
service_cidr: 100.64.0.0/13
enable_audit_logging: "true"
enable_ceip_participation: "true"
enable_mhc: "true"
mhc_unknown_status_timeout: 5m
mhc_false_status_timeout: 12m
identity_management_type: vsphere
infrastructure_provider: vsphere

tkg_http_proxy_enabled: "false"
tkg_ip_family: ipv4

## Parameters to create the Custom storage class inside the TKC workload cluster
custom_storage_class_name: "dsr-app-storage"
storage_policy_name: "tanzu-sp"
reclaimpolicy_type: "Retain"
volumebindingmode: "WaitForFirstConsumer"

######################################################################
# Unused
# vsphere_control_plane_disk_gib: "40"
# vsphere_control_plane_endpoint: 
# vsphere_control_plane_mem_mib: "16384"
# vsphere_control_plane_num_cpus: "4"
# vsphere_insecure: "true"
# vsphere_worker_disk_gib: "40"
# vsphere_worker_mem_mib: "4096"
# vsphere_worker_num_cpus: "2"
# vip_network_interface: "eth0"

# certificate_email: "me@vmware.com"