---
vsphere_server: "vc01.h2o-75-9210.h2o.vmware.com"
vsphere_username: "administrator@vsphere.local"
vsphere_password: "qBO2OA3Rf7e1X@leQdp"
tkg_user: "tkg-admin"
# Note that the password must conform to the vSphere user password policy.
tkg_user_password: "qBO2OA3Rf7e1X@leQdp"
tkg_role: TKG
cluster_name: vc01cl01
cluster_plan: dev
vsphere_namespace: "tkgs-ns1"
vsphere_namespace_owner: "Administrator"
vsphere_namespace_owner_domain: "vsphere.local"
#supervisor_cluster: "vc01cl01-wcp.h2o-75-9210.h2o.vmware.com"
supervisor_cluster: "10.220.47.3"
workload_cluster: "tkgs-workload2"
vsphere_datacenter: vc01
storage_class: "vc01cl01-t0compute"
datastore: "vsanDatastore"
#datastores: [vsanDatastore]
resource_pool: tkg-management-components
#resource_pools: [tkg-management-components]
vm_folder: tkg-management-components
#vm_folders: [tkg-management-components] 
network: "Avi Internal"
#networks: ["Avi Internal"]
distributed_switch: "vc01-dvs"
#distributed_switches: [vc01-dvs]

# Network settings for the Supervisor cluster...
supervisor_distributed_port_group: esxi-mgmt
supervisor_network_name: "esxi-mgmt"
supervisor_network_starting_ip: "10.220.30.150"
supervisor_network_subnet_mask: "255.255.255.224"
supervisor_network_gateway_ip: "10.220.30.158"
supervisor_network_static_address_count: "5"

# Workload network
primary_workload_network_static_gateway_ipv4: "10.220.47.62"
primary_workload_network_static_starting_address_ipv4: "10.220.47.12"
primary_workload_network_static_address_count: "50"
primary_workload_network_static_subnet_mask: "255.255.255.192"
primary_workload_network_vsphere_portgroup_name: "user-workload"

# Data network (VIP network)
data_network_static_starting_address_ipv4: "10.220.47.1"
data_network_static_address_count: "11"

dns_servers: "10.79.2.6"
#dns_servers: "10.220.136.2 10.220.136.3"
#dns_servers: "10.220.136.3"
dns_search_domain: "h2o-75-9210.h2o.vmware.com"
ntp_servers: "10.188.26.119"
#ntp_servers: "time1.oc.vmware.com, time2.oc.vmware.com, time3.oc.vmware.com, time4.oc.vmware.com"
content_library: "vc01cl01-wcp"

needed_privileges_file: needed_privileges.yaml

tanzu_config_template: tanzu_cluster_template.yaml
tanzu_mc_config_filename: tanzu_mgmt_cluster.yaml

cp_vmclass_size: "best-effort-medium"
control_plane_count: "1"
worker_node_count: "3"
worker_vmclass_size: "best-effort-medium"
ctrd_disksize: "25Gi"
kubelet_disksize: "15Gi"
tkr: "v1.22.9---vmware.1-tkg.1.cc71bc8"

vsphere_control_plane_disk_gib: "40"
vsphere_control_plane_endpoint: 
vsphere_control_plane_mem_mib: "16384"
vsphere_control_plane_num_cpus: "4"
vsphere_insecure: "true"
vsphere_worker_disk_gib: "40"
vsphere_worker_mem_mib: "4096"
vsphere_worker_num_cpus: "2"
vip_network_interface: "eth0"

tanzu_package_registry: "projects.registry.vmware.com/tkg/packages/standard/repo"
tanzu_package_registry_version: "v1.6.1"
tanzu_standard_package_repo_name: "tanzupackages"
installed_packages_namespace: "tanzu-packages"

certificate_email: "me@vmware.com"

avi_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDyzCCArOgAwIBAgIUWm5BrpRNRQFocULP5AxaPjPE854wDQYJKoZIhvcNAQEL
  BQAwgYMxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJDQTESMBAGA1UEBwwJUGFsbyBB
  bHRvMQ8wDQYDVQQKDAZWTXdhcmUxDDAKBgNVBAsMA0gyTzEOMAwGA1UEAwwFYXZp
  MDExJDAiBgkqhkiG9w0BCQEWFXBlenN1cHBvcnRAdm13YXJlLmNvbTAeFw0yMzAz
  MjcxODE4MTlaFw0yNDAzMjYxODE4MTlaMIGDMQswCQYDVQQGEwJVUzELMAkGA1UE
  CAwCQ0ExEjAQBgNVBAcMCVBhbG8gQWx0bzEPMA0GA1UECgwGVk13YXJlMQwwCgYD
  VQQLDANIMk8xDjAMBgNVBAMMBWF2aTAxMSQwIgYJKoZIhvcNAQkBFhVwZXpzdXBw
  b3J0QHZtd2FyZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8
  gg1/R01hMpqEYE2BCXlgQFpU/Bc9C2obprlc4wjp3xnwHd0261AjRNZuAgWSLfuF
  gt912NPHl2kjfXifNVQD+VXdXzLVVDs/5AkMkoP0rDOVcyaPYhehBiHgAnJAD1o+
  quUS5ivHisNptSIecSPTaWTVdJnTij19sUvLQDdeEUrNHawCiOg/yKCVW2RUVZZM
  0VsxcTd62079VCL1tT5y0sMNv0h/BD1PPVIGVywWm0+r9+BnUwQrtpUkN3J6Fq74
  ZWnptcyh/uBmuL6umbr+YWvVyEPDY9OX/zJWocr0AxedXPcHJvFq5OrrjieRZ0Ix
  EJhyZbDFv/lpESju58vNAgMBAAGjNTAzMDEGA1UdEQQqMCiCIGF2aTAxLmgyby03
  NS05MjEwLmgyby52bXdhcmUuY29thwQK3B6CMA0GCSqGSIb3DQEBCwUAA4IBAQCv
  4TMQFg6HrlFmDvHq5XHVsDXrIBGbudqMvSP3lrqY75b/AuESFZOlZWZ1DLugs/5j
  bNVKn2iVwHrnvvW9HPLgUNuMT/ldKg5fH0MDLtZoKobJaScxim8sS+m/okH71NlR
  WIAw0QJcRMBQIhP335YkDJncqur5qonAz0di/CrJ+8s1xV69K4OY5N6M38IkkXWW
  xeeoMsryBxXh3asrkPuq4KGvVHINNnq5jmKkxNX/9YeQn8dsphtQNf794ZO/hNYm
  V1+Pm2MQM8upB3JXc+9UBJFwcCVU7VXG+8+OAT3iB6bw0k4DbkMuYu4GN3e3xqdi
  vTYonv7wt7qKhBaVWgkA
  -----END CERTIFICATE-----
# Complete these in order to complete the tanzu build template yaml...
avi_controller_ip: "avi01.h2o-75-9210.h2o.vmware.com"
avi_username: "admin"
avi_password: "qBO2OA3Rf7e1X@leQdp"

# Unused below here
avi_ca_data_b64: 
avi_cloud_name: 
avi_control_plane_ha_provider: "true"
avi_controller: 
avi_data_network: 
avi_data_network_cidr: 
avi_enable: "true"
avi_labels: ""
avi_management_cluster_vip_network_name: 
avi_management_cluster_vip_network_cidr: 
avi_service_engine_group: 

cluster_cidr: 100.96.0.0/11
service_cidr: 100.64.0.0/13
enable_audit_logging: "true"
enable_ceip_participation: "true"
enable_mhc: "true"
mhc_unknown_status_timeout: 5m
mhc_false_status_timeout: 12m
identity_management_type: vsphere
infrastructure_provider: vsphere

tkg_http_proxy_enabled: "false"
tkg_ip_family: ipv4
